language: shell

services:
  - docker

before_install:
  - chmod +x check.sh
  - chmod +x lint.sh
  - chmod +x build.sh
  - chmod +x dist.sh


jobs:
  include:
    - stage: Preflight
      script:
        - $TRAVIS_BUILD_DIR/.travis/check.sh
      env:
        - SCRIPT=check
    - stage: Preflight
      script:
        - $TRAVIS_BUILD_DIR/.travis/lint.sh
      env:
        - SCRIPT=hadolint
    - stage: Build Docker Images
      script:
        - $TRAVIS_BUILD_DIR/.travis/build.sh
    - stage: Deploy Docker Images to Docker Hub
      if: type != pull_request AND tag IS present
      script:
        - $TRAVIS_BUILD_DIR/.travis/dist.sh